Updates ready for v0.1.8-Beta
bitwarden/helm-charts pull request #64
Opened 2023-11-30 15:30 UTC by jhbeskow

Fixing tag overrides.

Updating Application Gateway README steps.

Increasing resources for API and Identity pods.

2023-11-30 15:31 UTC, jhbeskow commented
The checks will likely fail due to the missing images.

2023-12-04 14:56 UTC, vgrassia commented on charts/self-host/README.md
> +Application Gateway ingress deployments have a few more required step for Bitwarden to function correctly.  If you are using another ingress controller, you may skip to the next section.
```suggestion
Application Gateway ingress deployments have a few more required steps for Bitwarden to function correctly.  If you are using another ingress controller, you may skip to the next section.
```

2023-12-04 14:58 UTC, vgrassia commented on charts/self-host/README.md
> +We will need finish the rewrite set on the Application Gateway we created earlier.
```suggestion
We will need to finish the rewrite set on the Application Gateway we created earlier.
```

2023-12-04 14:59 UTC, vgrassia commented on charts/self-host/README.md
> +  2. On the "Update rewrite set" page in the "Name and Association" tab, select all routing paths that begin with pr-bitwarden-self-host-ingress... , de-select any that do not begin with that prefix,
```suggestion
  2. On the "Update rewrite set" page in the "Name and Association" tab, select all routing paths that begin with pr-bitwarden-self-host-ingress... , deselect any that do not begin with that prefix, and then select Next.
```

2023-12-04 14:59 UTC, vgrassia commented on charts/self-host/README.md
> +  3. On the "Rewrite rule configuration" tab, click the "Add rewrite rule" button
```suggestion
  3. On the "Rewrite rule configuration" tab, click the "Add rewrite rule" button.
```

2023-12-04 14:59 UTC, vgrassia commented on charts/self-host/README.md
> +  4. Enter a name for the rule.  This can be anything that helps you with organization.  Something simlar to "bitwarden-rewrite" will work.
```suggestion
  4. Enter a name for the rule.  This can be anything that helps you with organization.  Something similar to "bitwarden-rewrite" will work.
```

2023-12-04 15:00 UTC, vgrassia commented on charts/self-host/README.md
> +  8. Click "Update" at the bottom of the screen
```suggestion
  8. Click "Update" at the bottom of the screen.
```

2023-12-04 15:00 UTC, vgrassia commented on charts/self-host/templates/admin.yaml
> +        image: "{{ .Values.component.admin.image.name }}:{{ default ( include "bitwarden.coreVersionDefault" nil ) .Values.general.coreVersionOverride}}"
```suggestion
        image: "{{ .Values.component.admin.image.name }}:{{ default ( include "bitwarden.coreVersionDefault" nil ) .Values.general.coreVersionOverride }}"
```

2023-12-04 15:00 UTC, vgrassia commented on charts/self-host/templates/api.yaml
> +        image: "{{ .Values.component.api.image.name }}:{{ default ( include "bitwarden.coreVersionDefault" nil ) .Values.general.coreVersionOverride}}"
```suggestion
        image: "{{ .Values.component.api.image.name }}:{{ default ( include "bitwarden.coreVersionDefault" nil ) .Values.general.coreVersionOverride }}"
```

2023-12-04 15:00 UTC, vgrassia commented on charts/self-host/templates/attachments.yaml
> +        image: "{{ .Values.component.attachments.image.name }}:{{ default ( include "bitwarden.coreVersionDefault" nil ) .Values.general.coreVersionOverride}}"
```suggestion
        image: "{{ .Values.component.attachments.image.name }}:{{ default ( include "bitwarden.coreVersionDefault" nil ) .Values.general.coreVersionOverride }}"
```

2023-12-04 15:01 UTC, vgrassia commented on charts/self-host/templates/events.yaml
> +        image: "{{ .Values.component.events.image.name }}:{{ default ( include "bitwarden.coreVersionDefault" nil ) .Values.general.coreVersionOverride}}"
```suggestion
        image: "{{ .Values.component.events.image.name }}:{{ default ( include "bitwarden.coreVersionDefault" nil ) .Values.general.coreVersionOverride }}"
```

2023-12-04 15:01 UTC, vgrassia commented on charts/self-host/templates/icons.yaml
> +        image: "{{ .Values.component.icons.image.name }}:{{ default ( include "bitwarden.coreVersionDefault" nil ) .Values.general.coreVersionOverride}}"
```suggestion
        image: "{{ .Values.component.icons.image.name }}:{{ default ( include "bitwarden.coreVersionDefault" nil ) .Values.general.coreVersionOverride }}"
```

2023-12-04 15:01 UTC, vgrassia commented on charts/self-host/templates/identity.yaml
> +        image: "{{ .Values.component.identity.image.name }}:{{ default ( include "bitwarden.coreVersionDefault" nil ) .Values.general.coreVersionOverride}}"
```suggestion
        image: "{{ .Values.component.identity.image.name }}:{{ default ( include "bitwarden.coreVersionDefault" nil ) .Values.general.coreVersionOverride }}"
```

2023-12-04 15:01 UTC, vgrassia commented on charts/self-host/templates/notifications.yaml
> +        image: "{{ .Values.component.notifications.image.name }}:{{ default ( include "bitwarden.coreVersionDefault" nil ) .Values.general.coreVersionOverride}}"
```suggestion
        image: "{{ .Values.component.notifications.image.name }}:{{ default ( include "bitwarden.coreVersionDefault" nil ) .Values.general.coreVersionOverride }}"
```

2023-12-04 15:01 UTC, vgrassia commented on charts/self-host/templates/post-install-db-migrator-job.yaml
> +        image: "bitwarden/mssqlmigratorutility:{{ default ( include "bitwarden.coreVersionDefault" nil ) .Values.general.coreVersionOverride}}"
```suggestion
        image: "bitwarden/mssqlmigratorutility:{{ default ( include "bitwarden.coreVersionDefault" nil ) .Values.general.coreVersionOverride }}"
```

2023-12-04 15:02 UTC, vgrassia commented on charts/self-host/templates/pre-install-db-migrator-job.yaml
> +        image: "bitwarden/mssqlmigratorutility:{{default ( include "bitwarden.coreVersionDefault" nil ) .Values.general.coreVersionOverride}}"
```suggestion
        image: "bitwarden/mssqlmigratorutility:{{default ( include "bitwarden.coreVersionDefault" nil ) .Values.general.coreVersionOverride }}"
```

2023-12-04 15:02 UTC, vgrassia commented on charts/self-host/templates/scim.yaml
> +        image: "{{ .Values.component.scim.image.name }}:{{ default ( include "bitwarden.coreVersionDefault" nil ) .Values.general.coreVersionOverride}}"
```suggestion
        image: "{{ .Values.component.scim.image.name }}:{{ default ( include "bitwarden.coreVersionDefault" nil ) .Values.general.coreVersionOverride }}"
```

2023-12-04 15:02 UTC, vgrassia commented on charts/self-host/templates/sso.yaml
> +        image: "{{ .Values.component.sso.image.name }}:{{ default ( include "bitwarden.coreVersionDefault" nil ) .Values.general.coreVersionOverride}}"
```suggestion
        image: "{{ .Values.component.sso.image.name }}:{{ default ( include "bitwarden.coreVersionDefault" nil ) .Values.general.coreVersionOverride }}"
```

2023-12-04 15:05 UTC, vgrassia commented on charts/self-host/templates/helpers.tpl
> +{{- default ( include "bitwarden.webVersionDefault" nil ) .Values.webVersionOverride  -}}
```suggestion
{{- default ( include "bitwarden.webVersionDefault" nil ) .Values.general.webVersionOverride  -}}
```

It looks like this is still under the `general` section in the `values` file.

2023-12-04 15:39 UTC, jhbeskow commented on charts/self-host/templates/helpers.tpl
> +{{- default ( include "bitwarden.webVersionDefault" nil ) .Values.webVersionOverride  -}}
Yes, I missed rolling it back after doing some testing.  Good catch.

2023-12-04 16:11 UTC, vgrassia requested changes

2023-12-04 16:11 UTC, vgrassia commented on charts/self-host/templates/helpers.tpl
> +{{- default ( include "bitwarden.webVersionDefault" nil ) .Values.webVersionOverride  -}}
Should this suggestion be applied? It seems like it should based on your reply unless I'm misunderstanding.

2023-12-04 16:20 UTC, merged